return {
  require("plugins.colorscheme"),
  require("plugins.treesitter"),
  require("plugins.mason"),
  require("plugins.lsp"),
  require("plugins.cmp"),
  require("plugins.conform"),
  require("plugins.telescope"),
  require("plugins.oil"),
  require("plugins.lint"),
  require("plugins.gitsigns"),
  require("plugins.markdown"),
  require("plugins.otter"),
  require("plugins.iron"),
  require("plugins.quarto"),
}
